server:
  port: 8999

spring:
  application:
    name: user-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8999/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  config:
    import: optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECURE_KEYS}
  access-token-expiration: 3600000  # 액세스 토큰 만료 시간 (예: 1시간)
  refresh-token-expiration: 86400000  # 리프레시 토큰 만료 시간 (예: 24시간)

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true   # Registers the service using its IP address
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30