server:
  port: 8999


spring:
  application:
    name: user-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8999/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true   # Registers the service using its IP address
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30